trigger:
- master

pool:
  vmImage: "vs2017-win2016"

variables:
  buildConfiguration: 'Release'

stages:
# Should we do the testing before?

#- template: build-webapps.yml
#  parameters:
#    stageName: 'Build_WebApps'
#    pathPrefix: 'WebApps'

- template: build-webjobs.yml
  parameters:
    stageName: 'Build_WebJobs'
    pathPrefix: 'WebJobs'
    webjobTypes: 
    - Continuous

#- template: build-functions.yml
#  parameters:
#    stageName: 'Build_Functions'
#    pathPrefix: 'Functions'

- stage: TMP_Stage
  dependsOn: 
  - Build_WebJobs
  jobs:
  - job: TMP_Job
    strategy:
      maxParallel: 2
      matrix: 
        debug:
          BuildConfiguration: debug
    
    steps:

    - task: PowerShell@2
      displayName: 'Print Artifacts'
      inputs:
        targetType: 'inline'
        workingDirectory: $(Pipeline.Workspace)
        script: |
            dir