trigger:
- master

pool:
  vmImage: "vs2017-win2016"

variables:
  buildConfiguration: 'Release'

stages:

- template: build-webapps.yml
  parameters:
    stageName: 'Build_WebApps'
    pathPrefix: 'WebApps'

- template: build-webjobs.yml
  parameters:
    stageName: 'Build_WebJobs'
    pathPrefix: 'WebJobs'