parameters:  
  stageName: 'Build_WebApps'
  pathPrefix: 'WebApps'
  dependsOn: []

stages:

- stage: ${{ parameters.stageName }}
  dependsOn: ${{ parameters.dependsOn }}  
  jobs:
  - job: Build_WebApp
    strategy:
      maxParallel: 2
      matrix: 
        debug:
          BuildConfiguration: debug
        #release:
        #  BuildConfiguration: release

    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/WebApps/**/*.csproj'
      displayName: 'Restore Nuget Packages'

    #- task: DotNetCoreCLI@2
    #  inputs:
    #    command: 'build'
    #    projects: '**/WebApps/**/*.csproj'
    #    arguments: '--no-restore'
    #  displayName: 'Build projects'

    #- task: DotNetCoreCLI@2
    #  inputs:
    #    command: 'test'
    #    projects: '**/*Test.csproj'
    #    arguments: '--no-restore'
    #  displayName: 'Run Tests'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '**/WebApps/**/*.csproj'
        #arguments: '--configuration $(buildConfiguration) --no-restore'
        arguments: '-o $(Build.ArtifactStagingDirectory)/WebApps --no-restore'
        zipAfterPublish: true
        modifyOutputPath: true    
      displayName: 'Publish CustomerApi'

    - task: PublishBuildArtifacts@1
      displayName: Publish Artifacts
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)
        artifactName: $(Build.BuildNumber)
        publishLocation: Container