parameters:  
  stageName: 'Build_WebJobs'
  pathPrefix: 'Webjobs'
  dependsOn: []

stages:

- stage: ${{ parameters.stageName }}
  dependsOn: ${{ parameters.dependsOn }}  
  jobs:
  - job: Build_WebJob
    strategy:
      maxParallel: 2
      matrix: 
        debug:
          BuildConfiguration: debug
        #release:
        #  BuildConfiguration: release

    steps:
        - script: echo building webjobs...
        
        - task: DotNetCoreCLI@2
          displayName: 'dotnet build'
          inputs:
            command: 'build'
            projects: '**/WebJobs/**/**/*.csproj'
            #arguments: '--no-restore'

        - task: DotNetCoreCLI@2
          displayName: 'Run Tests'
          inputs:
            command: 'test'
            projects: '**/WebJobs/*Test.csproj'
            arguments: '--no-restore'

        - task: DotNetCoreCLI@2
          displayName: 'DotNetCoreCLI publish all'
          inputs:
            command: 'publish'
            publishWebProjects: false
            projects: '**/WebJobs/Continuous/**/*.csproj'
            arguments: '-o $(Build.ArtifactStagingDirectory)/Output/WebJobs'
            zipAfterPublish: false
            modifyOutputPath: true

        - task: PublishBuildArtifacts@1
          displayName: Publish Artifacts
          inputs:
            PathtoPublish: $(Build.ArtifactStagingDirectory)/OutPut
            ArtifactName: $(Build.BuildNumber)
            ArtifactType: Container