parameters:  
  stageName: 'Build_WebJobs'
  pathPrefix: 'Webjobs'
  dependsOn: []

stages:

- stage: ${{ parameters.stageName }}
  dependsOn: ${{ parameters.dependsOn }}  
  jobs:
  - job: Build_WebJob
    strategy:
      maxParallel: 2
      matrix: 
        debug:
          BuildConfiguration: debug
        release:
          BuildConfiguration: release

    steps:
        - script: echo building webjobs...

        #- task: DotNetCoreCLI@2
        #inputs:
        #command: 'build'
        #projects: '**/WebJobs/**/**/*.csproj'
        ##arguments: '--no-restore'
        #displayName: 'Build projects'