parameters:  
  stageName: 'Build_Functions'
  pathPrefix: 'Functions'
  dependsOn: []


stages:
- stage: ${{ parameters.stageName }}
  dependsOn: ${{ parameters.dependsOn }}  
  jobs:
  - job: Build_Functions
    strategy:
        maxParallel: 2
        matrix: 
        debug:
            BuildConfiguration: debug
        release:
            BuildConfiguration: release

    steps:
        - script: echo building functions...