parameters:  
  stageName: 'Build_WebJobs'
  pathPrefix: 'Webjobs'
  dependsOn: []

stages:

- stage: ${{ parameters.stageName }}
  dependsOn: ${{ parameters.dependsOn }}  
  jobs:
  - job: Build_WebJob
    strategy:
      maxParallel: 2
      matrix: 
        debug:
          BuildConfiguration: debug
        #release:
        #  BuildConfiguration: release

    steps:
        - script: echo building webjobs...
        
        - task: DotNetCoreCLI@2
          displayName: 'dotnet build'
          inputs:
            command: 'build'
            projects: '**/WebJobs/**/**/*.csproj'
            #arguments: '--no-restore'

        - task: DotNetCoreCLI@2
          displayName: 'Run Tests'
          inputs:
            command: 'test'
            projects: '**/WebJobs/*Test.csproj'
            arguments: '--no-restore'

        - task: DotNetCoreCLI@2
          displayName: 'DotNetCoreCLI publish all'
          inputs:
            command: 'publish'
            publishWebProjects: false
            projects: '**/WebJobs/Continuous/**/*.csproj'
            # The goal is this: Output/WebJobs/{PROJECT_NAME}/App_Data/jobs/continuous/{PROJECT_NAME}
            arguments: '-o $(Build.ArtifactStagingDirectory)/WebJobs'
            zipAfterPublish: false
            modifyOutputPath: true

        - script: dir

        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            workingDirectory: $(Build.ArtifactStagingDirectory)/WebJobs
            script: |
                 $folders = Get-ChildItem -dir | Select-Object Name
                 foreach ($folderName in $folders) {
                 $finalName = $folderName.Name
                 New-Item -Path .\output\$finalName\App_Data\jobs\continuous -ItemType Directory -Force
                 Move-Item -Path .\$finalName -Destination .\output\$finalName\App_Data\jobs\continuous\ -Force }

        - task: PublishBuildArtifacts@1
          displayName: Publish Artifacts
          inputs:
            PathtoPublish: $(Build.ArtifactStagingDirectory)/WebJobs
            ArtifactName: $(Build.BuildNumber)
            ArtifactType: Container