parameters:  
  stageName: 'Build_Functions'
  pathPrefix: 'Functions'

stages:
- stage: ${{ parameters.stageName }}
  jobs:
  - job: Build_Webjob
    strategy:
        maxParallel: 2
        matrix: 
        debug:
            BuildConfiguration: debug
        release:
            BuildConfiguration: release

        steps:

        - task: CmdLine@2
          inputs:
            script: 'echo Building Functions...' 