parameters:  
  stageName: 'Run_Tests'
  dependsOn: []
  excludeProjects: string

stages:

- stage: ${{ parameters.stageName }}
  dependsOn: ${{ parameters.dependsOn }}  
  jobs:
  - job: Run_Tests

    steps:

    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: 'Tests/**/*Test.csproj'
      displayName: 'Restore Nuget Packages'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'Tests/**/*Test.csproj'
        arguments: '--no-restore'
      displayName: 'Build projects'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: Tests/**/*Test.csproj;!Tests/CustomerApi.Service.Test/*Test.csproj
        arguments: '--no-restore'
      displayName: 'Run Tests'