parameters:  
  stageName: 'Run_Tests'
  dependsOn: []
  excludeProjects: string

stages:

- stage: ${{ parameters.stageName }}
  dependsOn: ${{ parameters.dependsOn }}  
  jobs:
  - job: Run_Tests

    steps:

    - task: DotNetCoreCLI@2
      displayName: 'Restore'
      inputs:
        command: 'restore'
        projects: |
         **/*.csproj
         ${{ parameters.excludeProjects }}

    #- task: DotNetCoreCLI@2
    #  inputs:
    #    command: 'build'
    #    projects: 'Tests/**/*Test.csproj'
    #    arguments: '--no-restore'
    #  displayName: 'Build projects'

    - task: DotNetCoreCLI@2
      displayName: 'Run Tests'
      inputs:
        command: 'test'
        projects: |
         **/*Test.csproj
         #!Tests/CustomerApi.Service.test/**
         ${{ parameters.excludeProjects }}
        arguments: '--no-restore'